/**
 * MindMapper.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CanvasStateDto } from './canvasStateDto';
import { NaiveCardDto } from './naiveCardDto';
import { NaiveOptionDto } from './naiveOptionDto';


export interface CompositeCanvasStateDtoRequest { 
    canvas?: CanvasStateDto;
    cards?: Array<NaiveCardDto> | null;
    options?: Array<NaiveOptionDto> | null;
}

